import type { Metadata } from "next";
import { HomepageLayout } from "./components/chat/ChatComponent";
import "./globals.css";
import "animate.css"
import SessionWrapper from "./components/auth/Sessionwrapper";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authoptions";
import { Getrooms } from "./actions/createchatroom";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await getServerSession(authOptions)
  

  return (
    <html lang="en">
      <body>
       <SessionWrapper session={session}>
        <HomepageLayout>
          {children}
          <Toaster position="top-right"/>
        </HomepageLayout>
        </SessionWrapper> 
        
          
      </body>
    </html>
  );
}
